apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: profile-pvc
spec:
  storageClassName: csi-rbd-3-sc # Or another allowed storage class
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
