apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fiola-pvc-final
  namespace: fenton-neuroscience
spec:
  storageClassName: csi-rbd-3-ssd-sc  # Request 200 GB
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
---

apiVersion: batch/v1
kind: Job
metadata:
  name: fiola-process-job
  namespace: fenton-neuroscience
spec:
  template:
    spec:
      restartPolicy: Never
      volumes:
        - name: persistent-storage
          persistentVolumeClaim:
            claimName: fiola-pvc-final
      containers:
        - name: fiola-process-container
          image: registry.hsrn.nyu.edu/vip/corelink-examples/fiola-pipeline-final:latest
          command: ["sh", "-c"]
          args:
            - |
              export PYTHONPATH=/usr/src/app/FIOLA:/usr/src/app/CaImAn:/usr/local/lib/python3.8/dist-packages:${PYTHONPATH}
              numactl --cpunodebind=0 --membind=0 python3.8 ./receive_then_fiola.py
              tail -f /dev/null
          resources:
            limits:
              nvidia.com/gpu: 1  # Limit 1 NVIDIA GPU
              cpu: "16"          # Limit 16 CPUs
              memory: "64Gi"     # Limit 64Gi memory
            requests:
              nvidia.com/gpu: 1  # Request 1 NVIDIA GPU
              cpu: "16"          # Request 16 CPUs
              memory: "64Gi"     # Request 64Gi memory
          env:
            - name: TF_FORCE_GPU_ALLOW_GROWTH
              value: "true"
            - name: TF_GPU_THREAD_MODE
              value: "gpu_private"
          volumeMounts:
            - name: persistent-storage
              mountPath: /persistent_storage
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - "hsrn-ed10d-7e12"  # Replace with your specific node name
      tolerations:
        - key: nvidia.com/gpu
          operator: Exists
          effect: NoSchedule
  backoffLimit: 0
